/** Vocabulary is intentionally disjoint so an identifier's kind can be recognized without context. */
export const CONVERSATION_ID_ADJECTIVES = [
  "airy", "amber", "ancient", "awkward", "azure", "balmy", "bold", "bouncy", "brave", "breezy",
  "bright", "brisk", "bubbly", "bucolic", "caffeinated", "calm", "candid", "cheerful", "chill", "clear",
  "clever", "cloudy", "coastal", "cool", "cosmic", "cozy", "crafty", "crazy", "crisp", "curious",
  "dainty", "dappled", "daring", "dashing", "dejected", "devoted", "distant", "dramatic", "dreamy", "eager",
  "electric", "enchanted", "epic", "even", "fae", "fiery", "fleet", "floaty", "fluffy", "fresh",
  "friendly", "frosty", "funny", "fuzzy", "garbled", "gargantuan", "gentle", "giant", "gleaming", "glowing",
  "golden", "goofy", "graceful", "groovy", "happy", "hardy", "hidden", "hollow", "hushed", "icy",
  "impish", "ivory", "jaunty", "jazzy", "jolly", "keen", "kind", "leafy", "lively", "local",
  "lucid", "lucky", "lunar", "magical", "mellow", "merry", "misty", "modest", "moonlit", "mossy",
  "musical", "nimble", "noble", "oceanic", "peaceful", "peachy", "perky", "playful", "plucky", "polished",
  "quiet", "quirky", "radiant", "rapid", "rosy", "rustic", "sage", "serene", "sharp", "silent",
  "silver", "sleepy", "smooth", "snappy", "snowy", "solar", "sparkly", "spiffy", "spry", "squiggly",
  "steady", "stellar", "stringy", "sunny", "sweet", "swift", "tedious", "tender", "tiny", "tranquil",
  "twinkly", "upbeat", "velvety", "vivid", "warm", "watchful", "wavy", "wild", "wise", "witty",
  "wonky", "zany", "zesty", "zingy",
] as const;

export const CONVERSATION_ID_NOUNS = [
  "acorn", "alpaca", "antelope", "aster", "axolotl", "badger", "beaver", "beetle", "birch", "bison",
  "blob", "blossom", "bluebird", "bobcat", "bonsai", "breeze", "brook", "bubble", "bunny", "canyon",
  "capybara", "cardinal", "cedar", "cherry", "chime", "cloud", "clover", "comet", "coral", "coyote",
  "crane", "creek", "cricket", "dahlia", "dandelion", "dewdrop", "dolphin", "dragon", "duck", "dusk",
  "eagle", "echo", "elf", "ember", "faerie", "falcon", "fern", "finch", "firefly", "forest",
  "fox", "galaxy", "garden", "gecko", "geode", "glacier", "gnome", "gong", "goose", "grove",
  "harbor", "hawk", "hedgehog", "herb", "heron", "hill", "hummingbird", "iris", "island", "jay",
  "jellyfish", "juniper", "kestrel", "kimono", "kitten", "kiwi", "koala", "koan", "koi", "kumquat",
  "lagoon", "lake", "lantern", "lark", "lemur", "lion", "lotus", "mandala", "mango", "mantra",
  "maple", "marigold", "marmot", "meadow", "mesa", "mitten", "mochi", "moonbeam", "mountain", "mouse",
  "mushroom", "narwhal", "nebula", "newt", "oak", "orchid", "origami", "osprey", "otter", "owl",
  "panda", "pebble", "penguin", "pine", "pixie", "planet", "plume", "pond", "poppy", "prairie",
  "puffin", "quartz", "quokka", "rabbit", "raccoon", "raven", "reef", "river", "robin", "rocket",
  "salmon", "sequoia", "shell", "shore", "sloth", "sparrow", "sprite", "star", "stardust", "stick",
  "stone", "storm", "stream", "summit", "swan", "teacup", "thunder", "toadstool", "turtle", "willow",
  "wisp", "wombat", "zafu", "zephyr",
] as const;
