/** Vocabulary is intentionally disjoint so an identifier's kind can be recognized without context. */
export const CONVERSATION_ID_ADJECTIVES = [
  "agile", "airy", "amber", "ancient", "awkward", "azure", "balmy", "blissful", "bold", "bouncy",
  "brave", "breezy", "bright", "brisk", "bubbly", "bucolic", "buoyant", "caffeinated", "calm", "candid",
  "careful", "cautious", "cheerful", "chill", "chilly", "clear", "clever", "cloudy", "coastal", "confident",
  "cosmic", "coy", "cozy", "crafty", "crazy", "creative", "crisp", "curious", "cute", "dainty",
  "dappled", "daring", "dashing", "defiant", "deft", "dejected", "delicate", "delightful", "devoted", "distant",
  "dizzy", "dramatic", "dreamlike", "dreamy", "drowsy", "dusty", "dynamic", "eager", "electric", "elegant",
  "enchanted", "enchanting", "energetic", "epic", "ethereal", "even", "exuberant", "faithful", "fanciful", "fiery",
  "flawless", "floaty", "fluffy", "fresh", "friendly", "frosty", "funny", "fuzzy", "garbled", "gargantuan",
  "gentle", "giant", "gleaming", "gleeful", "glowing", "golden", "goofy", "graceful", "groovy", "happy",
  "hardy", "hidden", "hollow", "hushed", "icy", "impish", "intuitive", "ivory", "jaunty", "jazzy",
  "jolly", "jubilant", "keen", "kind", "leafy", "lively", "local", "lucid", "lucky", "lunar",
  "magical", "mellow", "merry", "mindful", "misty", "modest", "moonlit", "mossy", "musical", "natural",
  "neat", "nimble", "noble", "nostalgic", "observant", "oceanic", "patient", "peaceful", "peachy", "perky",
  "placid", "playful", "plucky", "polished", "precise", "quiet", "quirky", "radiant", "rapid", "restful",
  "rosy", "rustic", "sage", "sassy", "saucy", "serene", "sharp", "silent", "silver", "sleepy",
  "sly", "smooth", "snappy", "snazzy", "sneaky", "sneaky", "snoozy", "snowy", "snugly", "soft",
  "solar", "solid", "soothing", "sparkling", "sparkly", "spicy", "spiffy", "spry", "squiggly", "steady",
  "stellar", "stinky", "stringy", "sunny", "sweet", "swift", "tedious", "tender", "tiny", "tireless",
  "tranquil", "twinkly", "upbeat", "velvety", "vivacious", "vivid", "warm", "watchful", "wavy", "weary",
  "whimsical", "wild", "willing", "wise", "wistful", "witty", "wonky", "zany", "zesty", "zingy",
] as const;

export const CONVERSATION_ID_NOUNS = [
  "acorn", "alpaca", "antelope", "aster", "aurora", "avocado", "axolotl", "badger", "beaver", "beetle",
  "bicep", "birch", "bison", "blimp", "blob", "blossom", "bluebird", "bobcat", "bonsai", "branch",
  "breeze", "brew", "brook", "brush", "bubble", "bundle", "bunny", "canyon", "capybara", "cardinal",
  "cedar", "cello", "chant", "cherry", "chime", "clarinet", "cloud", "clover", "cluster", "comet",
  "coral", "coyote", "crane", "creek", "cricket", "dahlia", "dance", "dandelion", "dawn", "daydream",
  "dewdrop", "dinghy", "dolphin", "draft", "dragon", "dream", "drift", "duck", "dusk", "dusk",
  "eagle", "echo", "eclipse", "elf", "ember", "faerie", "falcon", "fern", "finch", "firefly",
  "flow", "flute", "forest", "fox", "frolic", "galaxy", "garden", "gazelle", "gecko", "geode",
  "glacier", "gnome", "gondola", "gong", "goose", "grove", "harbor", "hawk", "hedgehog", "herb",
  "heron", "hill", "hum", "hummingbird", "iris", "island", "jay", "jellyfish", "juniper", "kayak",
  "kestrel", "kimono", "kitten", "kiwi", "koala", "koan", "koi", "kumquat", "lagoon", "lake",
  "lantern", "lark", "lemur", "lion", "llama", "lotus", "mandala", "mango", "mantra", "maple",
  "marigold", "marmot", "meadow", "mesa", "mitten", "mochi", "moonbeam", "moonset", "mountain", "mouse",
  "muse", "mushroom", "narwhal", "nebula", "newt", "oak", "octopus", "orchid", "origami", "osprey",
  "otter", "owl", "panda", "pebble", "penguin", "pine", "pixie", "planet", "plume", "pond",
  "poppy", "prairie", "puffin", "quartz", "quokka", "rabbit", "raccoon", "raven", "reef", "river",
  "robin", "rocket", "route", "salmon", "saxophone", "sequoia", "shell", "shore", "sloth", "sparkle",
  "sparrow", "sprite", "star", "stardust", "stick", "stingray", "stone", "storm", "stream", "submarine",
  "summit", "sunet", "sunrise", "swan", "swordfish", "teacup", "thunder", "toadstool", "trombone", "trumpet",
  "turtle", "violin", "whisper", "willow", "wisp", "wombat", "xylophone", "zephyr",
] as const;
