/** Vocabulary is intentionally disjoint so an identifier's kind can be recognized without context. */
export const CONVERSATION_ID_ADJECTIVES = [
  "airy", "amber", "ancient", "azure", "bold", "bouncy", "brave", "breezy", "bright", "brisk",
  "bubbly", "bucolic", "calm", "candid", "cheerful", "chill", "clear", "clever", "cloudy", "coastal",
  "cool", "cozy", "crafty", "crisp", "curious", "dainty", "dappled", "daring", "dashing", "devoted",
  "distant", "dreamy", "eager", "electric", "epic", "even", "fiery", "fleet", "fluffy", "fresh",
  "friendly", "frosty", "funny", "fuzzy", "gentle", "giant", "gleaming", "glowing", "golden", "goofy",
  "graceful", "groovy", "happy", "hardy", "hidden", "hollow", "icy", "ivory", "jaunty", "jazzy",
  "jolly", "keen", "kind", "leafy", "lively", "local", "lucid", "lucky", "lunar", "magical",
  "mellow", "merry", "misty", "modest", "mossy", "musical", "nimble", "noble", "oceanic", "olive",
  "peaceful", "peachy", "perky", "playful", "plucky", "polished", "quiet", "quirky", "radiant", "rapid",
  "rosy", "rustic", "sage", "serene", "sharp", "silent", "silver", "sleepy", "smooth", "snappy",
  "snowy", "solar", "sparkly", "spiffy", "spry", "steady", "stellar", "sunny", "sweet", "swift",
  "tender", "tiny", "tranquil", "twinkly", "upbeat", "vivid", "warm", "watchful", "wavy", "wild",
  "wise", "witty", "wonky", "zesty", "zingy",
] as const;

export const CONVERSATION_ID_NOUNS = [
  "acorn", "alpaca", "antelope", "aster", "axolotl", "badger", "beaver", "beetle", "birch", "bison",
  "blob", "blossom", "bluebird", "bobcat", "breeze", "brook", "bunny", "canyon", "capybara", "cardinal",
  "cedar", "cherry", "cloud", "clover", "comet", "coral", "coyote", "crane", "creek", "cricket",
  "dahlia", "dandelion", "dolphin", "dragon", "duck", "dusk", "eagle", "ember", "falcon", "fern",
  "finch", "firefly", "forest", "fox", "galaxy", "garden", "gecko", "geode", "glacier", "goose",
  "grove", "harbor", "hawk", "hedgehog", "heron", "hill", "hummingbird", "iris", "island", "jay",
  "jellyfish", "juniper", "kestrel", "kitten", "koala", "koi", "lagoon", "lake", "lantern", "lark",
  "lemur", "lion", "lotus", "mango", "maple", "marigold", "marmot", "meadow", "mesa", "mochi",
  "moon", "mountain", "mouse", "narwhal", "nebula", "newt", "oak", "orchid", "osprey", "otter",
  "owl", "panda", "pebble", "penguin", "pine", "planet", "plume", "pond", "poppy", "prairie",
  "puffin", "quartz", "quokka", "rabbit", "raccoon", "raven", "reef", "river", "robin", "rocket",
  "salmon", "sequoia", "shell", "shore", "sloth", "sparrow", "star", "stone", "storm", "stream",
  "summit", "swan", "turtle", "willow", "wombat",
] as const;

export const RUN_ID_VERBS = [
  "adapt", "align", "analyze", "apply", "assemble", "assess", "audit", "authorize", "automate", "balance",
  "benchmark", "bootstrap", "branch", "browse", "build", "bundle", "cache", "calculate", "calibrate", "capture",
  "catalog", "chart", "check", "classify", "clone", "cluster", "collect", "combine", "compare", "compile",
  "complete", "compose", "compress", "compute", "configure", "confirm", "connect", "consolidate", "construct", "contrast",
  "convert", "coordinate", "correlate", "crawl", "create", "customize", "debug", "decode", "deduce", "deliver",
  "deploy", "design", "diagnose", "diagram", "diff", "discover", "dispatch", "distill", "distribute", "document",
  "draft", "edit", "engineer", "enumerate", "estimate", "evaluate", "execute", "expand", "explore", "export",
  "extract", "filter", "finish", "fix", "format", "gather", "generate", "grep", "guide", "identify",
  "implement", "import", "improve", "index", "infer", "initialize", "inspect", "integrate", "investigate", "isolate",
  "iterate", "join", "launch", "link", "lint", "load", "locate", "log", "map", "match",
  "measure", "merge", "migrate", "model", "monitor", "navigate", "optimize", "orchestrate", "organize", "package",
  "parse", "patch", "pinpoint", "plan", "polish", "predict", "prepare", "prioritize", "process", "prototype",
  "publish", "query", "rank", "reconcile", "record", "recover", "reduce", "refactor", "refine", "reload",
  "render", "repair", "resolve", "restructure", "retrieve", "review", "revise", "route", "run", "sample",
  "scan", "schedule", "script", "scrub", "search", "select", "sequence", "ship", "simplify", "simulate",
  "solve", "sort", "split", "stage", "streamline", "summarize", "sync", "synthesize", "tally", "target",
  "test", "tokenize", "trace", "track", "train", "transform", "translate", "troubleshoot", "tune", "update",
  "upgrade", "validate", "verify", "write", "yield", "zoom",
] as const;

export const RUN_ID_ADVERBS = [
  "ably", "abruptly", "accurately", "actively", "adaptively", "agilely", "analytically", "aptly", "automatically", "boldly",
  "breezily", "brightly", "briskly", "calmly", "carefully", "cautiously", "certainly", "cleanly", "clearly", "closely",
  "coherently", "collaboratively", "concisely", "concurrently", "confidently", "conservatively", "consistently", "constructively", "continuously", "correctly",
  "creatively", "crisply", "critically", "deeply", "deftly", "deliberately", "dependably", "deterministically", "diligently", "directly",
  "dynamically", "easily", "efficiently", "elegantly", "evenly", "exactly", "expertly", "explicitly", "faithfully", "fast",
  "firmly", "flawlessly", "flexibly", "fluently", "freely", "freshly", "fully", "gently", "gladly", "gracefully",
  "helpfully", "honestly", "immediately", "incrementally", "independently", "intelligently", "intentionally", "intuitively", "iteratively", "keenly",
  "lightly", "locally", "logically", "loosely", "manually", "methodically", "meticulously", "minimally", "modularly", "natively",
  "naturally", "neatly", "objectively", "observantly", "openly", "optimally", "orderly", "patiently", "plainly", "practically",
  "precisely", "predictably", "proactively", "productively", "progressively", "promptly", "properly", "purposefully", "quickly", "rapidly",
  "readily", "recursively", "reliably", "repeatedly", "responsively", "rigorously", "robustly", "routinely", "safely", "seamlessly",
  "securely", "separately", "sharply", "silently", "simply", "skillfully", "slowly", "smartly", "smoothly", "snappily",
  "softly", "solidly", "soundly", "speedily", "squarely", "stably", "steadily", "strategically", "strictly", "strongly",
  "successfully", "succinctly", "surely", "systematically", "tactically", "technically", "tersely", "thoroughly", "thoughtfully", "tightly",
  "tirelessly", "transparently", "truly", "uniformly", "usefully", "visibly", "warmly", "widely", "willingly", "wisely",
  "yearly",
] as const;
